### ISSUE TITLE
求php版本客户端

### ISSUE THREAD

**Issue by youjiawang** [XiaoMi/pegasus#173]
客户端没有php的版本么？

**Comment by neverchanje** [comment]
Sorry, we don't have a php client now, because in XiaoMi we don't have such requirement.
But it's in our plan to figure out the current C++ driver into a cleaner C driver, which your php application can direcly call.

It's not a strong requirement now, you can post a pull request for this and we are glad to accept it.

**Comment by shengofsun** [comment]
这边人手不足，近期支持php客户端可能有些困难。如果有兴趣的话，你可以帮我们开发一个 :-)
可以参考的资料有：
* [rpc协议](https://github.com/XiaoMi/pegasus/blob/master/docs/client-development.md)
* [java客户端的代码](https://github.com/XiaoMi/pegasus-java-client)
